<?php

/**
 * @file
 * Contains http_client_welcome.module.
 */


/**
 * Implements hook_theme().
 */
function http_client_welcome_theme($existing, $type, $theme, $path) {
  return [
    'http_client_welcome_posts_list' => [
      'variables' => [
        'posts'  => [
          'side' => NULL,
          'year' => NULL,
          'miles' => NULL,
          'gas' => NULL,
        ],       
      ],
    ],    
  ];
}
